development:
  adapter: postgresql
  encoding: unicode
  database: manifesto_development
  pool: 5
  username: postgres
  password: password

test:
  adapter: postgresql
  encoding: unicode
  database: manifesto_test
  pool: 5
  username: postgres
  password: password